### ISSUE TITLE
Route only a specific subnet

### ISSUE THREAD

**Issue by ahmednrana** [yabeenico/wsshuttle#2]
Is it possible to route only 10.0.0.0 traffic through the ssh server.
e.g. 
Machine A (local machine) IP is 192.168.1.2
Machine B (remote machine which the Machine A can login using ssh) is 192.168.1.3
B has access to 10.0.0.0.
How can I access the 10.0.0.0 using A.

**Comment by yabeenico** [comment]
This may work.

```
Machine-A $ wsshuttle -r 192.168.1.3 10.0.0.0/8
```
