### ISSUE TITLE
I get route.exe parameter incorrect

### ISSUE THREAD

**Issue by Svetoslav92** [yabeenico/wsshuttle#3]
Hi,
I'm on win10 and using the command in the same way as in the readme. In the place of ssh_server I just place my ip address of the remote host and get connected message but beforehand I get:

root@DESKTOP:/mnt/c/Windows/system32# wsshuttle -r 12.12.12.12 -x 157.0.0.0/8 0/0
The route addition failed: The parameter is incorrect.

This makes me think this project was developed on win11 ? Was it tried with lower version of route.exe or why is that problem?

Thanks

**Comment by yabeenico** [comment]
The project is currently being developed on win11, but there is no particular change from when it was developed on win10

Run `wsshuttle -r 12.12.12.12 -x 157.0.0.0/8 0/0 --dry` and please show me log.
