### ISSUE TITLE
fails to properly pass --ssh-cmd to sshuttle

### ISSUE THREAD

**Issue by devonjones** [yabeenico/wsshuttle#4]
$ wsshuttle --dns -vr [fakeuser]@[fakeip] 10.200.0.0/16 --ssh-cmd 'ssh -i ~/.ssh/[somespecialkey]-id_rsa'

sshuttle -l 0.0.0.0:0 --dns -vr [fakeuser]@[fakeip] 10.200.0.0/16 --ssh-cmd ssh -i ~/.ssh/[somespecialkey]-id_rsa
usage: sshuttle [-l [ip:]port] [-r [user@]sshserver[:port]] <subnets...>
sshuttle: error: unrecognized arguments: -i /home/devon/.ssh/[somespecialkey]-id_rsa

**Comment by devonjones** [comment]
these args normally work with sshuttle

**Comment by yabeenico** [comment]
Resolved.
