### ISSUE TITLE
Invalid delete mask commands

### ISSUE THREAD

**Issue by WoutDev** [yabeenico/wsshuttle#9]
Host environment: Windows 11, WSL2

WSL2 enviromnent:
> uname -r
```
5.15.146.1-microsoft-standard-WSL2+
```

> lsb_release -a
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy
```

Command executed:
> wsshuttle -r username@hostname 0/0 --dry

Output:
```
route.exe  delete  mask
route.exe  add     mask  192.168.123.170  metric  1  if  21
sshuttle -l 0.0.0.0:0 -r username@resolved-ip 0/0
route.exe  delete  mask
```

The problem seems to be with the "delete mask" commands that lack arguments. Indeed, without '--dry':
> The route addition failed: De parameter is onjuist.

The second part roughly translates to "The parameter is incorrect."

**Comment by yabeenico** [comment]
The specified range `0/0` includes `resolved-ip`, so you have to exclude `resolved-ip` by `-x`.

Try

```
wsshuttle -r username@hostname 0/0 -x `resolved-ip`
```
